// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: automations.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AutomationEnvelope provides a container for the JSON representation of an Automation.
type AutomationEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// automation_json stores the Automation serialized as a JSON string.
	AutomationJson string `protobuf:"bytes,1,opt,name=automation_json,json=automationJson,proto3" json:"automation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutomationEnvelope) Reset() {
	*x = AutomationEnvelope{}
	mi := &file_automations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationEnvelope) ProtoMessage() {}

func (x *AutomationEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_automations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationEnvelope.ProtoReflect.Descriptor instead.
func (*AutomationEnvelope) Descriptor() ([]byte, []int) {
	return file_automations_proto_rawDescGZIP(), []int{0}
}

func (x *AutomationEnvelope) GetAutomationJson() string {
	if x != nil {
		return x.AutomationJson
	}
	return ""
}

var File_automations_proto protoreflect.FileDescriptor

const file_automations_proto_rawDesc = "" +
	"\n" +
	"\x11automations.proto\x12\vautomations\"=\n" +
	"\x12AutomationEnvelope\x12'\n" +
	"\x0fautomation_json\x18\x01 \x01(\tR\x0eautomationJsonB$Z\"opsicle/internal/automations/pb;pbb\x06proto3"

var (
	file_automations_proto_rawDescOnce sync.Once
	file_automations_proto_rawDescData []byte
)

func file_automations_proto_rawDescGZIP() []byte {
	file_automations_proto_rawDescOnce.Do(func() {
		file_automations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_automations_proto_rawDesc), len(file_automations_proto_rawDesc)))
	})
	return file_automations_proto_rawDescData
}

var file_automations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_automations_proto_goTypes = []any{
	(*AutomationEnvelope)(nil), // 0: automations.AutomationEnvelope
}
var file_automations_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_automations_proto_init() }
func file_automations_proto_init() {
	if File_automations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_automations_proto_rawDesc), len(file_automations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_automations_proto_goTypes,
		DependencyIndexes: file_automations_proto_depIdxs,
		MessageInfos:      file_automations_proto_msgTypes,
	}.Build()
	File_automations_proto = out.File
	file_automations_proto_goTypes = nil
	file_automations_proto_depIdxs = nil
}
