version: '3.8'

services:
  # opsicle:
  #   build:
  #     context: .
  #     target: final
  #   image: opsicle:local
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_USERNAME: opsicle
  #     REDIS_PASSWORD: StrongPassword123
  #   ports:
  #     - "8080:8080"

  mysql:
    image: mysql:8
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opsicle
      MYSQL_USER: opsicle
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/.mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: cache
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/.redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/.redis/data/redis-data:/data

volumes:
  redis-data:
