// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: coordinator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb "opsicle/internal/automations/pb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetNextJobRequest identifies the worker requesting a job.
type GetNextJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker_id indicates which worker is requesting work.
	WorkerId      string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextJobRequest) Reset() {
	*x = GetNextJobRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextJobRequest) ProtoMessage() {}

func (x *GetNextJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextJobRequest.ProtoReflect.Descriptor instead.
func (*GetNextJobRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *GetNextJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// GetNextJobResponse contains the automation payload for the worker to execute.
type GetNextJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// automation holds the JSON representation of the Automation that should be executed next.
	Automation    *pb.AutomationEnvelope `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextJobResponse) Reset() {
	*x = GetNextJobResponse{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextJobResponse) ProtoMessage() {}

func (x *GetNextJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextJobResponse.ProtoReflect.Descriptor instead.
func (*GetNextJobResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *GetNextJobResponse) GetAutomation() *pb.AutomationEnvelope {
	if x != nil {
		return x.Automation
	}
	return nil
}

// UpdateExecutionRequest reports execution progress and logs for an Automation.
type UpdateExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker_id indicates which worker is reporting the execution updates.
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// automation_id identifies the Automation execution instance.
	AutomationId string `protobuf:"bytes,2,opt,name=automation_id,json=automationId,proto3" json:"automation_id,omitempty"`
	// status provides the latest execution status as reported by the worker.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// log_entries contains the log lines emitted during execution.
	LogEntries    []*ExecutionLogEntry `protobuf:"bytes,4,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionRequest) Reset() {
	*x = UpdateExecutionRequest{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionRequest) ProtoMessage() {}

func (x *UpdateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateExecutionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *UpdateExecutionRequest) GetAutomationId() string {
	if x != nil {
		return x.AutomationId
	}
	return ""
}

func (x *UpdateExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateExecutionRequest) GetLogEntries() []*ExecutionLogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

// ExecutionLogEntry captures a single log line produced during execution.
type ExecutionLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp_unix records when the log entry was created in seconds since epoch.
	TimestampUnix int64 `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// level represents the severity level (e.g. info, warn, error) of the log entry.
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// message holds the textual log content.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLogEntry) Reset() {
	*x = ExecutionLogEntry{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLogEntry) ProtoMessage() {}

func (x *ExecutionLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLogEntry.ProtoReflect.Descriptor instead.
func (*ExecutionLogEntry) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionLogEntry) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ExecutionLogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ExecutionLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateExecutionResponse acknowledges receipt of execution updates.
type UpdateExecutionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted indicates whether the update was successfully processed.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionResponse) Reset() {
	*x = UpdateExecutionResponse{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionResponse) ProtoMessage() {}

func (x *UpdateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateExecutionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\x1a,internal/automations/proto/automations.proto\"0\n" +
	"\x11GetNextJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"U\n" +
	"\x12GetNextJobResponse\x12?\n" +
	"\n" +
	"automation\x18\x01 \x01(\v2\x1f.automations.AutomationEnvelopeR\n" +
	"automation\"\xb3\x01\n" +
	"\x16UpdateExecutionRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rautomation_id\x18\x02 \x01(\tR\fautomationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12?\n" +
	"\vlog_entries\x18\x04 \x03(\v2\x1e.coordinator.ExecutionLogEntryR\n" +
	"logEntries\"j\n" +
	"\x11ExecutionLogEntry\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"5\n" +
	"\x17UpdateExecutionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xc5\x01\n" +
	"\x12CoordinatorService\x12O\n" +
	"\n" +
	"GetNextJob\x12\x1e.coordinator.GetNextJobRequest\x1a\x1f.coordinator.GetNextJobResponse0\x01\x12^\n" +
	"\x0fUpdateExecution\x12#.coordinator.UpdateExecutionRequest\x1a$.coordinator.UpdateExecutionResponse0\x01B$Z\"opsicle/internal/coordinator/pb;pbb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_coordinator_proto_goTypes = []any{
	(*GetNextJobRequest)(nil),       // 0: coordinator.GetNextJobRequest
	(*GetNextJobResponse)(nil),      // 1: coordinator.GetNextJobResponse
	(*UpdateExecutionRequest)(nil),  // 2: coordinator.UpdateExecutionRequest
	(*ExecutionLogEntry)(nil),       // 3: coordinator.ExecutionLogEntry
	(*UpdateExecutionResponse)(nil), // 4: coordinator.UpdateExecutionResponse
	(*pb.AutomationEnvelope)(nil),   // 5: automations.AutomationEnvelope
}
var file_coordinator_proto_depIdxs = []int32{
	5, // 0: coordinator.GetNextJobResponse.automation:type_name -> automations.AutomationEnvelope
	3, // 1: coordinator.UpdateExecutionRequest.log_entries:type_name -> coordinator.ExecutionLogEntry
	0, // 2: coordinator.CoordinatorService.GetNextJob:input_type -> coordinator.GetNextJobRequest
	2, // 3: coordinator.CoordinatorService.UpdateExecution:input_type -> coordinator.UpdateExecutionRequest
	1, // 4: coordinator.CoordinatorService.GetNextJob:output_type -> coordinator.GetNextJobResponse
	4, // 5: coordinator.CoordinatorService.UpdateExecution:output_type -> coordinator.UpdateExecutionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
